require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HrTablesColumnsController do

  # This should return the minimal set of attributes required to create a valid
  # HrTablesColumn. As you add validations to HrTablesColumn, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HrTablesColumnsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hr_tables_columns as @hr_tables_columns" do
      hr_tables_column = HrTablesColumn.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hr_tables_columns).should eq([hr_tables_column])
    end
  end

  describe "GET show" do
    it "assigns the requested hr_tables_column as @hr_tables_column" do
      hr_tables_column = HrTablesColumn.create! valid_attributes
      get :show, {:id => hr_tables_column.to_param}, valid_session
      assigns(:hr_tables_column).should eq(hr_tables_column)
    end
  end

  describe "GET new" do
    it "assigns a new hr_tables_column as @hr_tables_column" do
      get :new, {}, valid_session
      assigns(:hr_tables_column).should be_a_new(HrTablesColumn)
    end
  end

  describe "GET edit" do
    it "assigns the requested hr_tables_column as @hr_tables_column" do
      hr_tables_column = HrTablesColumn.create! valid_attributes
      get :edit, {:id => hr_tables_column.to_param}, valid_session
      assigns(:hr_tables_column).should eq(hr_tables_column)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HrTablesColumn" do
        expect {
          post :create, {:hr_tables_column => valid_attributes}, valid_session
        }.to change(HrTablesColumn, :count).by(1)
      end

      it "assigns a newly created hr_tables_column as @hr_tables_column" do
        post :create, {:hr_tables_column => valid_attributes}, valid_session
        assigns(:hr_tables_column).should be_a(HrTablesColumn)
        assigns(:hr_tables_column).should be_persisted
      end

      it "redirects to the created hr_tables_column" do
        post :create, {:hr_tables_column => valid_attributes}, valid_session
        response.should redirect_to(HrTablesColumn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hr_tables_column as @hr_tables_column" do
        # Trigger the behavior that occurs when invalid params are submitted
        HrTablesColumn.any_instance.stub(:save).and_return(false)
        post :create, {:hr_tables_column => {}}, valid_session
        assigns(:hr_tables_column).should be_a_new(HrTablesColumn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HrTablesColumn.any_instance.stub(:save).and_return(false)
        post :create, {:hr_tables_column => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hr_tables_column" do
        hr_tables_column = HrTablesColumn.create! valid_attributes
        # Assuming there are no other hr_tables_columns in the database, this
        # specifies that the HrTablesColumn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HrTablesColumn.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => hr_tables_column.to_param, :hr_tables_column => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested hr_tables_column as @hr_tables_column" do
        hr_tables_column = HrTablesColumn.create! valid_attributes
        put :update, {:id => hr_tables_column.to_param, :hr_tables_column => valid_attributes}, valid_session
        assigns(:hr_tables_column).should eq(hr_tables_column)
      end

      it "redirects to the hr_tables_column" do
        hr_tables_column = HrTablesColumn.create! valid_attributes
        put :update, {:id => hr_tables_column.to_param, :hr_tables_column => valid_attributes}, valid_session
        response.should redirect_to(hr_tables_column)
      end
    end

    describe "with invalid params" do
      it "assigns the hr_tables_column as @hr_tables_column" do
        hr_tables_column = HrTablesColumn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HrTablesColumn.any_instance.stub(:save).and_return(false)
        put :update, {:id => hr_tables_column.to_param, :hr_tables_column => {}}, valid_session
        assigns(:hr_tables_column).should eq(hr_tables_column)
      end

      it "re-renders the 'edit' template" do
        hr_tables_column = HrTablesColumn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HrTablesColumn.any_instance.stub(:save).and_return(false)
        put :update, {:id => hr_tables_column.to_param, :hr_tables_column => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hr_tables_column" do
      hr_tables_column = HrTablesColumn.create! valid_attributes
      expect {
        delete :destroy, {:id => hr_tables_column.to_param}, valid_session
      }.to change(HrTablesColumn, :count).by(-1)
    end

    it "redirects to the hr_tables_columns list" do
      hr_tables_column = HrTablesColumn.create! valid_attributes
      delete :destroy, {:id => hr_tables_column.to_param}, valid_session
      response.should redirect_to(hr_tables_columns_url)
    end
  end

end
